Added Visualisation File type/widget/formatter
govCMS/dvf pull request #18
Opened 2018-05-18 05:43 UTC by jez500

Hi @tobybellwood & @jorgegc 

Can you please have a look at this one. The main change is DVF now supports file uploads rather than just a remote URL. This works really well with CSVs but will support anything really given the correct data  source.

Other Changes:
* Readme added! with some basic "how to use" instructions
* A number of bug fixes 
* Lots of coding standard fixes
* composer file added

I am keen to get this into my project asap and noted github has diverged a bit from drupal.org, happy to clone it in manually but ideally would be great to see drupal.org project updated with the most recent code.

Cheers

2018-05-18 07:29 UTC, jorgegc requested changes
Hey @jez500 very nice work!

There is one thing that I think we should consider adding to this PR before merging, and that is the common interface for Visualisation field types.

Please let me know your thoughts.

Cheers

2018-05-18 07:29 UTC, jorgegc commented on README.md
> +  `Visualisation File` depeing on if the data source will be local or remote,
~~depeing~~ depending

2018-05-18 07:29 UTC, jorgegc commented on src/FieldFormatterTrait.php
> +    /** @var \Drupal\dvf\Plugin\Field\FieldType\VisualisationUrlItem $item */
We can't type hint this as `\Drupal\dvf\Plugin\Field\FieldType\VisualisationUrlItem`. Ideally, these fields should share a common interface `VisualisationItem` which guarantees `VisualisationItem::getVisualisationPlugin` exists.

2018-05-18 07:29 UTC, jorgegc commented on src/Plugin/Field/FieldWidget/VisualisationFileWidget.php
> +    foreach ($values as &$value) {
Line break before control structures improves code readability.

2018-05-18 07:29 UTC, jorgegc commented on src/Plugin/Field/FieldWidget/VisualisationFileWidget.php
> +   * Form API callback. Retrieves the value for the file_generic field element.
`Form API callback: Retrieves the value for the file_generic field element.`?

2018-05-21 00:10 UTC, jez500 commented
Thanks for the feedback @jorgegc those changes have been addressed

FYI @tobybellwood

2018-05-21 00:28 UTC, jorgegc approved these changes

2018-05-21 08:36 UTC, tobybellwood commented
Cool - I'll merge here and push up to d.o. - the only difference up to now was the bundling of the submodules in the Github version wasn't reflected in d.o.

2018-05-21 08:38 UTC, merged

2018-05-21 09:27 UTC, tobybellwood commented
d.o. updated https://www.drupal.org/project/dvf/releases/8.x-1.x-dev (and updated dvf_ckan and dvf_csv to point to submodules of dvf instead)

2018-05-21 23:08 UTC, jez500 commented
Thanks @tobybellwood :)