Composerification
govCMS/dvf pull request #19
Opened 2018-05-21 08:41 UTC by tobybellwood

2018-07-02 23:47 UTC, jorgegc commented
Hi @tobybellwood there are a number of issues with this PR, including conflicts. This is blocking #4 so I think it is best if we close this one and incorporate these changes in my next PR. Thoughts?

2018-07-02 23:48 UTC, jorgegc requested changes

2018-07-02 23:48 UTC, jorgegc commented on composer.json
> +  "name": "govcms/dvf",
Why are we namespacing it under `govcms` and not `drupal`?

2018-07-02 23:48 UTC, jorgegc commented on composer.json
> +  "version": "0.0.1",
Version is not required.

2018-07-02 23:48 UTC, jorgegc commented on composer.json
> +  "prefer-stable": true,
This is not going to have any effect because `prefer-stable` is root-only.

2018-07-02 23:48 UTC, jorgegc commented on composer.json
> +  "require": { }
Empty `require` should be removed.

2018-07-03 00:02 UTC, tobybellwood commented
Happy to close and have a resubmit

2018-07-03 00:02 UTC, closed without merging