Expose DataTables customisation options
govCMS/dvf pull request #25
Opened 2018-07-03 02:15 UTC by rob-duplock

- Added page length and searching options.
- Refactored couple comments.
- Drupal coding standard updates.

2018-07-03 07:43 UTC, jorgegc requested changes
Sorry @rob-duplock I have left quite a few comments for you to address. I am being super strict because we area aiming for a release soon and I don't want anything to go in that we will need to change later.

2018-07-03 07:43 UTC, jorgegc commented on js/dvfTables.js
> +          tableId = $table.data('dvftables');
Can we undo this change please?

2018-07-03 07:43 UTC, jorgegc commented on src/Plugin/Visualisation/Style/Table.php
> +      '#description' => $this->t('Number of rows to display on a single page when using pagination.'),
Pagination is always enabled. Can we please change this to:

> Number of rows per page.

2018-07-03 07:43 UTC, jorgegc commented on src/Plugin/Visualisation/Style/Table.php
> +    $form['table']['table_options']['enable_searching'] = [
For consistency with the other settings, can this please be renamed to `searching`?

2018-07-03 07:43 UTC, jorgegc commented on src/Plugin/Visualisation/Style/Table.php
> +      '#title' => $this->t('Enable Searching'),
For consistency again, `Searching` should be lowercase.

2018-07-03 07:43 UTC, jorgegc commented on src/Plugin/Visualisation/Style/Table.php
> +   * Returns Page length options.
`Returns page length options.`

2018-07-03 07:43 UTC, jorgegc commented on src/Plugin/Visualisation/Style/Table.php
> +   *   Page length options.
`An array of page length options.`

2018-07-03 07:43 UTC, jorgegc commented on src/Plugin/Visualisation/Style/Table.php
> +          'enable_searching' => TRUE,
`'searching' => TRUE,`

2018-07-03 07:43 UTC, jorgegc commented on src/Plugin/Visualisation/Style/Table.php
> +    $form['table']['table_options']['page_length'] = [
For consistency, we should put these settings under `Table options`

```
$form['table']['options'] = [
  '#type' => 'details',
  '#title' => $this->t('Table options'),
  '#tree' => TRUE,
];

$form['table']['options']['page_length'] = [
  ...
];

$form['table']['options']['searching_enabled'] = [
  ...
];
```

2018-07-03 07:43 UTC, jorgegc commented on src/Plugin/Visualisation/Style/TableVisualisationStyleBase.php
> +  abstract protected function getTableOptions();
This doesn't make any sense here because `TableVisualisationStyleBase.php` doesn't have a settings form. Could you please remove it?

2018-07-03 07:43 UTC, jorgegc commented on src/Plugin/Visualisation/Style/TableVisualisationStyleBase.php
> +  protected function parseTableOptions() {
This doesn't make any sense here either. Please remove.

2018-07-03 07:43 UTC, jorgegc commented on src/Plugin/Visualisation/Style/TableVisualisationStyleBase.php
> +      'tableOptions' => $this->parseTableOptions(),
Can we please remove this line from here and add the following to `Table.php` below `Table::rowHeaderField`?

```
/**
 * {@inheritdoc}
 */
protected function tableBuildSettings(array $records) {
  $settings = parent::tableBuildSettings($records);

  $settings['tableOptions']['pageLength'] = $this->config('table', 'options', 'page_length');
  $settings['tableOptions']['searching'] = $this->config('table', 'options', 'searching');

  return $settings;
}
```

2018-07-03 07:43 UTC, jorgegc commented on src/Plugin/Visualisation/Style/Table.php
> +        'table_options' => [
`'options' => [`

2018-07-03 07:43 UTC, jorgegc commented on js/jquery.dvfTables.js
> +        .getTableOptions()
For consistency, this should be `.parseTableOptions`.

2018-07-03 07:43 UTC, jorgegc commented on js/jquery.dvfTables.js
> +    getTableOptions: function () {
Can we please rename this to `parseTableOptions`?

2018-07-03 07:43 UTC, jorgegc commented on js/jquery.dvfTables.js
> +      this.config = $.extend(this.config, this.options.tableOptions);
After all my suggestions `this.options.tableOptions` may not be set so we need to check before using it.

```
parseTableOptions: function () {
  if (this.options.tableOptions) {
    this.config = $.extend(this.config, this.options.tableOptions);
  }

  return this;
}
```

2018-07-03 07:43 UTC, jorgegc commented on src/Plugin/Visualisation/Style/Table.php
> +  protected function getTableOptions() {
This can be removed. Please see my comments below.

2018-07-04 01:32 UTC, rob-duplock commented
Thanks @jorgegc please see latest commit.

2018-07-05 00:33 UTC, jorgegc approved these changes
Solid work @rob-duplock. Sorry about the annoying comments!

2018-07-05 07:36 UTC, tobybellwood approved these changes
I'm happy for @jorgegc to merge.

2018-07-05 07:56 UTC, merged