Add support for gauge chart type
govCMS/dvf pull request #26
Opened 2018-07-03 02:43 UTC by rob-duplock

- Added support for gauge chart type
- Refactored from existing PR with improvements / coding standard fixes

2018-07-03 04:21 UTC, jez500 commented on js/jquery.dvfCharts.js
> +    parseGaugeOptions: function () {
I know this is just following suit with Jorges zero comments in Javascript :P but I feel every method should have at least one comment describing its purpose and in cases like this a link to the c3js reference.

eg 
```
/**
 * Parse user settings into object suitable for use with Gauge Chart.
 *
 * @example https://c3js.org/samples/chart_gauge.html
 * @see https://c3js.org/reference.html#gauge-label-show
 */
parseGaugeOptions: function () {
  ...
}
```

2018-07-03 04:22 UTC, jez500 approved these changes
Looks good apart from my comment gripe :)

2018-07-03 04:29 UTC, jez500 commented
Have also asked @rob-duplock to ensure the split field works with this so it doesn't have to solely rely on totals

2018-07-03 07:47 UTC, jorgegc approved these changes
Looking good @rob-duplock. Nice work!

2018-07-05 00:41 UTC, jorgegc requested changes
@rob-duplock and I had a chat about a small bug we found with split fields and gauge charts. He will update the PR shortly.

2018-07-05 00:56 UTC, rob-duplock commented
I have added the split field bugfix.
It should also be noted the best gauge chart experience relies on having the[ C3 and D3 libraries updated to the latest version](https://github.com/govCMS/dvf/pull/24).

2018-07-05 01:40 UTC, jorgegc approved these changes
Thanks @rob-duplock. Looks good!

2018-07-05 07:36 UTC, tobybellwood approved these changes
I'm happy for @jorgegc to merge.

2018-07-05 07:57 UTC, merged